#!/bin/sh

NODE_ENV="production"
PORT="443"
APP_DIR="/var/www/directsend"
NODE_APP="app.js"
CONFIG_DIR="$APP_DIR"
PID_DIR="$APP_DIR/pid"
PID_FILE="$PID_DIR/app.pid"
LOG_DIR="$APP_DIR/log"
LOG_FILE="$LOG_DIR/app.log"
NODE_EXEC=$(which node)

###############

# REDHAT chkconfig header

# chkconfig: - 58 74
# description: directsend
### BEGIN INIT INFO
# Provides: node
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: directsend
# Description: directsend
### END INIT INFO

###############

USAGE="usage: $0 {start|stop|restart|status} [--force]"
FORCE_OP=false

pid_file_exists() {
    [ -f "$PID_FILE" ]
}

get_pid() {
    echo "$(cat "$PID_FILE")"
}

is_running() {
    PID=$(get_pid)
    ! [ -z "$(ps aux | awk '{print $2}' | grep "^$PID$")" ]
}

start_it() {
    mkdir -p "$PID_DIR"
    mkdir -p "$LOG_DIR"

    echo "starting directsend ..."
    PORT="$PORT" NODE_ENV="$NODE_ENV" NODE_CONFIG_DIR="$CONFIG_DIR" $NODE_EXEC "$APP_DIR/$NODE_APP"  1>"$LOG_FILE" 2>&1 &
    echo $! > "$PID_FILE"
    echo "directsend started with pid $!"
}

stop_process() {
    PID=$(get_pid)
    echo "killing process $PID"
    kill $PID
}

remove_pid_file() {
    echo "removing pid file"
    rm -f "$PID_FILE"
}

start_app() {
    if pid_file_exists
    then
        if is_running
        then
            PID=$(get_pid)
            echo "directsend already running with pid $PID"
            exit 1
        else
            echo "directsend stopped, but pid file exists"
            if [ $FORCE_OP = true ]
            then
                echo "forcing start anyways"
                remove_pid_file
                start_it
            fi
        fi
    else
        start_it
    fi
}

stop_app() {
    if pid_file_exists
    then
        if is_running
        then
            echo "stopping directsend ..."
            stop_process
            remove_pid_file
            echo "directsend stopped"
        else
            echo "directsend already stopped, but pid file exists"
            if [ $FORCE_OP = true ]
            then
                echo "forcing stop anyways ..."
                remove_pid_file
                echo "directsend stopped"
            else
                exit 1
            fi
        fi
    else
        echo "directsend already stopped, pid file does not exist"
        exit 1
    fi
}

status_app() {
    if pid_file_exists
    then
        if is_running
        then
            PID=$(get_pid)
            echo "directsend running with pid $PID"
        else
            echo "directsend stopped, but pid file exists"
        fi
    else
        echo "directsend stopped"
    fi
}

case "$2" in
    --force)
        FORCE_OP=true
    ;;

    "")
    ;;

    *)
        echo $USAGE
        exit 1
    ;;
esac

case "$1" in
    start)
        start_app
    ;;

    stop)
        stop_app
    ;;

    restart)
        stop_app
        start_app
    ;;

    status)
        status_app
    ;;

    *)
        echo $USAGE
        exit 1
    ;;
esac
